/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javataxibooking;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author praty
 */
public class Taxi extends javax.swing.JFrame {
    JFrame f = new JFrame();
    DefaultListModel BookedInfoModel = new DefaultListModel();
    DefaultListModel LogInfoModel = new DefaultListModel();
    String name = "";

    /**
     * Creates new form Taxi
     */
    public Taxi() {
        initComponents();
        LoginPanel.setVisible(true);
        BookingPanel.setVisible(false);
        StatusPanel.setVisible(false);
        AboutPanel.setVisible(false);
        RegistrationPanel.setVisible(false);
        navigator1.setBackground(Color.white);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        navigator1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        navigator2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        navigator3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        navigator4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        LPUtextLabel = new javax.swing.JLabel();
        lpuLogo = new javax.swing.JLabel();
        Container = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        MainPic = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        loginRegField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        loginPassField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        T_Cbutton = new javax.swing.JRadioButton();
        jLabel10 = new javax.swing.JLabel();
        goRegiText = new javax.swing.JLabel();
        BookingPanel = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        NameField = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        ContactField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        destinationp2 = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        Sourcep2 = new javax.swing.JComboBox<>();
        jLabel16 = new javax.swing.JLabel();
        BookButton = new javax.swing.JButton();
        fareField = new javax.swing.JTextField();
        StatusPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel5 = new javax.swing.JLabel();
        BookedInfo = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        jLabel17 = new javax.swing.JLabel();
        AboutPanel = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        RegistrationPanel = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        RegItemContainer = new javax.swing.JPanel();
        jLabel25 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        RegisterNo = new javax.swing.JTextField();
        RegisterName = new javax.swing.JTextField();
        RegisterPass1 = new javax.swing.JTextField();
        RegisterPass2 = new javax.swing.JPasswordField();
        RegisterButton = new javax.swing.JButton();
        T_C2 = new javax.swing.JRadioButton();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 623, Short.MAX_VALUE));
        jPanel2Layout.setVerticalGroup(
                jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 325, Short.MAX_VALUE));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 153, 0));

        navigator1.setBackground(new java.awt.Color(204, 204, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Log-in");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel1MousePressed(evt);
            }
        });

        javax.swing.GroupLayout navigator1Layout = new javax.swing.GroupLayout(navigator1);
        navigator1.setLayout(navigator1Layout);
        navigator1Layout.setHorizontalGroup(
                navigator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        navigator1Layout.setVerticalGroup(
                navigator1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE));

        navigator2.setBackground(new java.awt.Color(204, 204, 0));
        navigator2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                navigator2MousePressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Services");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel2MousePressed(evt);
            }
        });

        javax.swing.GroupLayout navigator2Layout = new javax.swing.GroupLayout(navigator2);
        navigator2.setLayout(navigator2Layout);
        navigator2Layout.setHorizontalGroup(
                navigator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        navigator2Layout.setVerticalGroup(
                navigator2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE));

        navigator3.setBackground(new java.awt.Color(204, 204, 0));
        navigator3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                navigator3MousePressed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Status");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel3MousePressed(evt);
            }
        });

        javax.swing.GroupLayout navigator3Layout = new javax.swing.GroupLayout(navigator3);
        navigator3.setLayout(navigator3Layout);
        navigator3Layout.setHorizontalGroup(
                navigator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        navigator3Layout.setVerticalGroup(
                navigator3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE));

        navigator4.setBackground(new java.awt.Color(204, 204, 0));

        jLabel4.setFont(new java.awt.Font("Segoe UI Historic", 3, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("About");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jLabel4MousePressed(evt);
            }
        });

        javax.swing.GroupLayout navigator4Layout = new javax.swing.GroupLayout(navigator4);
        navigator4.setLayout(navigator4Layout);
        navigator4Layout.setHorizontalGroup(
                navigator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        navigator4Layout.setVerticalGroup(
                navigator4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE));

        LPUtextLabel.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        LPUtextLabel.setForeground(new java.awt.Color(255, 255, 255));
        LPUtextLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LPUtextLabel.setText("LPU TAXI");

        lpuLogo.setForeground(new java.awt.Color(255, 51, 102));
        lpuLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lpuLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javataxibooking/lpuLogo.png"))); // NOI18N
        lpuLogo.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(navigator1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(navigator2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(navigator3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(navigator4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LPUtextLabel, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addComponent(lpuLogo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(48, 48, 48)));
        jPanel1Layout.setVerticalGroup(
                jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(lpuLogo, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(LPUtextLabel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(30, 30, 30)
                                .addComponent(navigator1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(navigator2, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(navigator3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(navigator4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(82, 82, 82)));

        LoginPanel.setBackground(new java.awt.Color(153, 255, 153));

        MainPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javataxibooking/col_21.jpg"))); // NOI18N

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));

        jLabel6.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Book Your Taxi ");

        jLabel7.setFont(new java.awt.Font("Segoe UI Emoji", 3, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Now");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(45, 45, 45)
                                                .addComponent(jLabel6))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addGap(96, 96, 96)
                                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 67,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel3Layout.setVerticalGroup(
                jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 37,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)));

        jPanel4.setBackground(new java.awt.Color(153, 255, 153));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Registration No.");

        loginRegField.setText("Enter Reg no.");
        loginRegField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                loginRegFieldFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                loginRegFieldFocusLost(evt);
            }
        });
        loginRegField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginRegFieldActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Password");

        loginButton.setText("Login");
        loginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginButtonMouseClicked(evt);
            }
        });

        T_Cbutton.setText("Accept T&C");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Don't have Account?");

        goRegiText.setBackground(new java.awt.Color(102, 102, 255));
        goRegiText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        goRegiText.setForeground(new java.awt.Color(102, 102, 255));
        goRegiText.setText("Register Now");
        goRegiText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                goRegiTextMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(46, 46, 46)
                                                .addGroup(jPanel4Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(jLabel8,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                99, Short.MAX_VALUE)
                                                                        .addComponent(jLabel9,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                Short.MAX_VALUE))
                                                                .addGap(18, 18, 18)
                                                                .addGroup(jPanel4Layout.createParallelGroup(
                                                                        javax.swing.GroupLayout.Alignment.LEADING,
                                                                        false)
                                                                        .addComponent(loginRegField,
                                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                                141, Short.MAX_VALUE)
                                                                        .addComponent(loginPassField)))
                                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                                .addGap(35, 35, 35)
                                                                .addComponent(T_Cbutton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 98,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(loginButton,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 65,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addGap(66, 66, 66)
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(goRegiText)))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        jPanel4Layout.setVerticalGroup(
                jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(loginRegField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53, 53))
                                        .addGroup(jPanel4Layout.createSequentialGroup()
                                                .addComponent(loginPassField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addGroup(jPanel4Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(loginButton, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(T_Cbutton))
                                                .addGap(24, 24, 24)))
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel10)
                                        .addComponent(goRegiText))
                                .addContainerGap()));

        javax.swing.GroupLayout LoginPanelLayout = new javax.swing.GroupLayout(LoginPanel);
        LoginPanel.setLayout(LoginPanelLayout);
        LoginPanelLayout.setHorizontalGroup(
                LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap())
                        .addComponent(MainPic, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        LoginPanelLayout.setVerticalGroup(
                LoginPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(LoginPanelLayout.createSequentialGroup()
                                .addComponent(MainPic, javax.swing.GroupLayout.PREFERRED_SIZE, 333, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(LoginPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));

        BookingPanel.setBackground(new java.awt.Color(204, 255, 255));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javataxibooking/lpu3.jpg"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(204, 255, 255));

        jLabel12.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel12.setText("Name:");

        NameField.setText("Your Name");
        NameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                NameFieldFocusGained(evt);
            }
        });
        NameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFieldActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel13.setText("Contact:");

        ContactField.setText("Enter Phone no.");
        ContactField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                ContactFieldFocusGained(evt);
            }
        });
        ContactField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactFieldActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel14.setText("Destination:");

        destinationp2.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Main Gate", "GH-4", "CSE-Block", "NK-Kitchen", "Uni-Hospital" }));

        jLabel15.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel15.setText("Source:");

        Sourcep2.setModel(new javax.swing.DefaultComboBoxModel<>(
                new String[] { "Main Gate", "GH-4", "CSE-Block", "NK-Kitchen", "Uni-Hospital" }));

        jLabel16.setFont(new java.awt.Font("Sitka Text", 1, 14)); // NOI18N
        jLabel16.setText("Fare:");

        BookButton.setText("Book Now");
        BookButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookButtonActionPerformed(evt);
            }
        });

        fareField.setEditable(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(210, 210, 210)
                                                .addGroup(jPanel5Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel13))
                                                .addGap(28, 28, 28)
                                                .addGroup(jPanel5Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(ContactField,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 162,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(NameField,
                                                                javax.swing.GroupLayout.Alignment.TRAILING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 162,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                .addGap(155, 155, 155)
                                                .addGroup(jPanel5Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel16)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addComponent(jLabel15)
                                                                .addGap(18, 18, 18)
                                                                .addComponent(Sourcep2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 106,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addGroup(jPanel5Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGap(18, 18, 18)
                                                                .addComponent(jLabel14)
                                                                .addPreferredGap(
                                                                        javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                                .addComponent(destinationp2,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 104,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel5Layout.createSequentialGroup()
                                                                .addGap(27, 27, 27)
                                                                .addComponent(fareField,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE, 71,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                .addContainerGap(123, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(BookButton)
                                .addGap(286, 286, 286)));
        jPanel5Layout.setVerticalGroup(
                jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel5Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(NameField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel13)
                                        .addComponent(ContactField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel14)
                                        .addComponent(destinationp2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Sourcep2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel15))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19,
                                        Short.MAX_VALUE)
                                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(fareField, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(BookButton)
                                .addContainerGap()));

        javax.swing.GroupLayout BookingPanelLayout = new javax.swing.GroupLayout(BookingPanel);
        BookingPanel.setLayout(BookingPanelLayout);
        BookingPanelLayout.setHorizontalGroup(
                BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BookingPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE));
        BookingPanelLayout.setVerticalGroup(
                BookingPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(BookingPanelLayout.createSequentialGroup()
                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 307, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        StatusPanel.setBackground(new java.awt.Color(153, 255, 204));

        jScrollPane1.setBackground(new java.awt.Color(51, 255, 204));
        jScrollPane1.setForeground(new java.awt.Color(102, 102, 102));

        jScrollPane1.setViewportView(jList1);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel5.setText("User's Logs");

        BookedInfo.setBackground(new java.awt.Color(51, 255, 204));
        BookedInfo.setForeground(new java.awt.Color(102, 102, 102));

        BookedInfo.setViewportView(jList2);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel17.setText("Bookings Info");

        javax.swing.GroupLayout StatusPanelLayout = new javax.swing.GroupLayout(StatusPanel);
        StatusPanel.setLayout(StatusPanelLayout);
        StatusPanelLayout.setHorizontalGroup(
                StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StatusPanelLayout.createSequentialGroup()
                                .addGap(112, 112, 112)
                                .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(235, 235, 235)
                                .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE, 133, Short.MAX_VALUE)
                                .addGap(106, 106, 106))
                        .addGroup(StatusPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(BookedInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 300,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        StatusPanelLayout.setVerticalGroup(
                StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(StatusPanelLayout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(StatusPanelLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 47,
                                                Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(
                                        StatusPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane1)
                                                .addComponent(BookedInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 266,
                                                        Short.MAX_VALUE))
                                .addGap(118, 118, 118)));

        AboutPanel.setBackground(new java.awt.Color(102, 0, 102));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(255, 255, 255));
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("This");

        jLabel19.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("IS");

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 3, 30)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("LOVELY PROFESSIONAL UNIVERSITY");

        jLabel21.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel21.setText("TAXI BOOKING APPLICATION");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel22.setText("ADVANCE JAVA PROJECT");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 2, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 102, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("MADE BY");

        jLabel24.setFont(new java.awt.Font("Sitka Text", 2, 24)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(204, 255, 204));
        jLabel24.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel24.setText("Pratyansh Maddheshia");

        javax.swing.GroupLayout AboutPanelLayout = new javax.swing.GroupLayout(AboutPanel);
        AboutPanel.setLayout(AboutPanelLayout);
        AboutPanelLayout.setHorizontalGroup(
                AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel18, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addComponent(jLabel20, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, 683, Short.MAX_VALUE)
                        .addComponent(jLabel21, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE)
                        .addGroup(AboutPanelLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(
                                        AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel22, javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jLabel23, javax.swing.GroupLayout.Alignment.TRAILING,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap())
                        .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                Short.MAX_VALUE));
        AboutPanelLayout.setVerticalGroup(
                AboutPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(AboutPanelLayout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(jLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, 46, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel20, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 27, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel22, javax.swing.GroupLayout.DEFAULT_SIZE, 28, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel23, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel24, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                                .addGap(86, 86, 86)));

        RegistrationPanel.setBackground(new java.awt.Color(204, 255, 153));
        RegistrationPanel.setForeground(new java.awt.Color(255, 153, 102));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javataxibooking/naac_header2.png"))); // NOI18N

        RegItemContainer.setBackground(new java.awt.Color(204, 255, 153));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel25.setText("Registration No.");

        jLabel27.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel27.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel27.setText("Name");

        jLabel28.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel28.setText("Password");

        jLabel29.setFont(new java.awt.Font("Segoe UI", 3, 12)); // NOI18N
        jLabel29.setText("ReEnter Password");

        RegisterNo.setText("Registration no.");
        RegisterNo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RegisterNoFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                RegisterNoFocusLost(evt);
            }
        });
        RegisterNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterNoActionPerformed(evt);
            }
        });

        RegisterName.setText("User Name");
        RegisterName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RegisterNameFocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                RegisterNameFocusLost(evt);
            }
        });
        RegisterName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterNameActionPerformed(evt);
            }
        });

        RegisterPass1.setText("Password");
        RegisterPass1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RegisterPass1FocusGained(evt);
            }

            public void focusLost(java.awt.event.FocusEvent evt) {
                RegisterPass1FocusLost(evt);
            }
        });

        RegisterPass2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                RegisterPass2FocusGained(evt);
            }
        });
        RegisterPass2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterPass2ActionPerformed(evt);
            }
        });

        RegisterButton.setFont(new java.awt.Font("Segoe UI Variable", 1, 12)); // NOI18N
        RegisterButton.setText("Register");
        RegisterButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RegisterButtonMouseClicked(evt);
            }
        });
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        T_C2.setText("I confirm That all mentioned details are correct");
        T_C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                T_C2ActionPerformed(evt);
            }
        });

        jLabel31.setText("Already Have Account?");

        jLabel32.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(102, 102, 255));
        jLabel32.setText("Log-in ");
        jLabel32.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel32MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout RegItemContainerLayout = new javax.swing.GroupLayout(RegItemContainer);
        RegItemContainer.setLayout(RegItemContainerLayout);
        RegItemContainerLayout.setHorizontalGroup(
                RegItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RegItemContainerLayout.createSequentialGroup()
                                .addGap(0, 118, Short.MAX_VALUE)
                                .addGroup(RegItemContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addGroup(RegItemContainerLayout.createSequentialGroup()
                                                .addGap(6, 6, 6)
                                                .addComponent(jLabel29)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(RegisterPass2, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(RegItemContainerLayout.createSequentialGroup()
                                                .addGroup(RegItemContainerLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel25)
                                                        .addComponent(jLabel28, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                102, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(28, 28, 28)
                                                .addGroup(RegItemContainerLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(RegisterNo,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 153,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(RegisterName,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 153,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(RegisterPass1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 153,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addComponent(T_C2))
                                .addGroup(RegItemContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(RegItemContainerLayout.createSequentialGroup()
                                                .addGap(67, 67, 67)
                                                .addComponent(jLabel31)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(jLabel32)
                                                .addContainerGap(41, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RegItemContainerLayout
                                                .createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        105, Short.MAX_VALUE)
                                                .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(60, 60, 60)))));
        RegItemContainerLayout.setVerticalGroup(
                RegItemContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RegItemContainerLayout.createSequentialGroup()
                                .addGroup(RegItemContainerLayout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(RegItemContainerLayout.createSequentialGroup()
                                                .addGap(16, 16, 16)
                                                .addGroup(RegItemContainerLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel25)
                                                        .addComponent(RegisterNo,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(RegItemContainerLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel27)
                                                        .addComponent(RegisterName,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(RegItemContainerLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(RegisterPass1,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel28))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(RegItemContainerLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(jLabel29)
                                                        .addComponent(RegisterPass2,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(RegItemContainerLayout.createSequentialGroup()
                                                .addGap(59, 59, 59)
                                                .addComponent(RegisterButton, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(RegItemContainerLayout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel31)
                                                        .addComponent(jLabel32))))
                                .addGap(18, 18, 18)
                                .addComponent(T_C2)
                                .addContainerGap(11, Short.MAX_VALUE)));

        javax.swing.GroupLayout RegistrationPanelLayout = new javax.swing.GroupLayout(RegistrationPanel);
        RegistrationPanel.setLayout(RegistrationPanelLayout);
        RegistrationPanelLayout.setHorizontalGroup(
                RegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                RegistrationPanelLayout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 682,
                                                Short.MAX_VALUE))
                        .addComponent(RegItemContainer, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        RegistrationPanelLayout.setVerticalGroup(
                RegistrationPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(RegistrationPanelLayout.createSequentialGroup()
                                .addComponent(jLabel26, javax.swing.GroupLayout.DEFAULT_SIZE, 307, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(RegItemContainer, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        javax.swing.GroupLayout ContainerLayout = new javax.swing.GroupLayout(Container);
        Container.setLayout(ContainerLayout);
        ContainerLayout.setHorizontalGroup(
                ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BookingPanel, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE))
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(StatusPanel, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE))
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AboutPanel, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE))
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RegistrationPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        ContainerLayout.setVerticalGroup(
                ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(LoginPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BookingPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(StatusPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(AboutPanel, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(ContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RegistrationPanel, javax.swing.GroupLayout.Alignment.TRAILING,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void loginRegFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_loginRegFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_loginRegFieldActionPerformed

    private void loginRegFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_loginRegFieldFocusGained
        if (loginRegField.getText().equals("Enter Reg no.")) {
            loginRegField.setText("");
        }
    }// GEN-LAST:event_loginRegFieldFocusGained

    private void loginRegFieldFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_loginRegFieldFocusLost
        if (loginRegField.getText().equals("")) {
            loginRegField.setText("Enter Reg no.");
        }
    }// GEN-LAST:event_loginRegFieldFocusLost

    private void jLabel1MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel1MousePressed
        activeLoginPanel();
    }// GEN-LAST:event_jLabel1MousePressed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_RegisterButtonActionPerformed

    private void T_C2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_T_C2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_T_C2ActionPerformed

    void activeLoginPanel() {
        LoginPanel.setVisible(true);
        BookingPanel.setVisible(false);
        StatusPanel.setVisible(false);
        AboutPanel.setVisible(false);
        RegistrationPanel.setVisible(false);
        navigator1.setBackground(Color.white);
        navigator2.setBackground(new Color(204, 204, 0));
        navigator3.setBackground(new Color(204, 204, 0));
        navigator4.setBackground(new Color(204, 204, 0));
    }

    void activeBooking() {
        LoginPanel.setVisible(false);
        BookingPanel.setVisible(true);
        StatusPanel.setVisible(false);
        AboutPanel.setVisible(false);
        RegistrationPanel.setVisible(false);
        navigator2.setBackground(Color.white);
        navigator1.setBackground(new Color(204, 204, 0));
        navigator3.setBackground(new Color(204, 204, 0));
        navigator4.setBackground(new Color(204, 204, 0));
    }

    void activeStatusPanel() {
        LoginPanel.setVisible(false);
        BookingPanel.setVisible(false);
        StatusPanel.setVisible(true);
        AboutPanel.setVisible(false);
        RegistrationPanel.setVisible(false);
        navigator3.setBackground(Color.white);
        navigator1.setBackground(new Color(204, 204, 0));
        navigator2.setBackground(new Color(204, 204, 0));
        navigator4.setBackground(new Color(204, 204, 0));
    }

    void activeAboutPanel() {
        LoginPanel.setVisible(false);
        BookingPanel.setVisible(false);
        StatusPanel.setVisible(false);
        AboutPanel.setVisible(true);
        RegistrationPanel.setVisible(false);
        navigator4.setBackground(Color.white);
        navigator1.setBackground(new Color(204, 204, 0));
        navigator3.setBackground(new Color(204, 204, 0));
        navigator2.setBackground(new Color(204, 204, 0));
    }

    void activeRegisterPanel() {
        LoginPanel.setVisible(false);
        BookingPanel.setVisible(false);
        StatusPanel.setVisible(false);
        AboutPanel.setVisible(false);
        RegistrationPanel.setVisible(true);
        navigator4.setBackground(new Color(204, 204, 0));
        navigator1.setBackground(new Color(204, 204, 0));
        navigator3.setBackground(new Color(204, 204, 0));
        navigator2.setBackground(new Color(204, 204, 0));
    }

    private void navigator2MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_navigator2MousePressed
        activeBooking();
    }// GEN-LAST:event_navigator2MousePressed

    private void navigator3MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_navigator3MousePressed
        // TODO add your handling code here:
    }// GEN-LAST:event_navigator3MousePressed

    private void jLabel2MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel2MousePressed
        activeBooking();
    }// GEN-LAST:event_jLabel2MousePressed

    private void jLabel3MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel3MousePressed
        activeStatusPanel();
    }// GEN-LAST:event_jLabel3MousePressed

    private void jLabel4MousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel4MousePressed
        activeAboutPanel();
    }// GEN-LAST:event_jLabel4MousePressed

    private void RegisterNoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RegisterNoActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_RegisterNoActionPerformed

    private void RegisterNameActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RegisterNameActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_RegisterNameActionPerformed

    private void loginButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_loginButtonMouseClicked
        if ("".equals(loginRegField.getText()) || "".equals(loginPassField.getText())
                || T_Cbutton.isSelected() == false) {
            JOptionPane.showMessageDialog(f, "Please fill in all fields.");
            return;
        }

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");

            String query = "SELECT * FROM users WHERE registration_number = ? AND password = ?";
            String username = loginRegField.getText();
            String userPassword = loginPassField.getText();
            System.out.print(username);
            System.out.print(userPassword);
            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "@Pm109305");
                    PreparedStatement pstmt = con.prepareStatement(query)) {

                pstmt.setString(1, username);
                pstmt.setString(2, userPassword);

                ResultSet rs = pstmt.executeQuery();
                if (rs.next()) {
                    JOptionPane.showMessageDialog(f, "Welcome Back " + rs.getString("name"));
                    name = rs.getString("name");
                    NameField.setText(name);
                    activeBooking();
                } else {
                    JOptionPane.showMessageDialog(f, "Invalid username or password");
                }

            } catch (SQLException e) {
                e.printStackTrace();
            }

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Taxi.class.getName()).log(Level.SEVERE, null, ex);
        }
    }// GEN-LAST:event_loginButtonMouseClicked

    private void goRegiTextMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_goRegiTextMouseClicked
        activeRegisterPanel();
    }// GEN-LAST:event_goRegiTextMouseClicked

    private void jLabel32MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jLabel32MouseClicked
        activeLoginPanel();
    }// GEN-LAST:event_jLabel32MouseClicked

    private void RegisterNoFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_RegisterNoFocusGained
        if (RegisterNo.getText().equals("Registration no.")) {
            RegisterNo.setText("");
        }
    }// GEN-LAST:event_RegisterNoFocusGained

    private void RegisterNoFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_RegisterNoFocusLost
        if (RegisterNo.getText().equals("")) {
            RegisterNo.setText("Registration no.");
        }
    }// GEN-LAST:event_RegisterNoFocusLost

    private void RegisterNameFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_RegisterNameFocusGained
        if (RegisterName.getText().equals("User Name")) {
            RegisterName.setText("");
        }
    }// GEN-LAST:event_RegisterNameFocusGained

    private void RegisterNameFocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_RegisterNameFocusLost
        if (RegisterName.getText().equals("")) {
            RegisterName.setText("User Name");
        }
    }// GEN-LAST:event_RegisterNameFocusLost

    private void RegisterPass1FocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_RegisterPass1FocusGained
        if (RegisterPass1.getText().equals("Password")) {
            RegisterPass1.setText("");
        }
    }// GEN-LAST:event_RegisterPass1FocusGained

    private void RegisterPass1FocusLost(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_RegisterPass1FocusLost
        if (RegisterPass1.getText().equals("")) {
            RegisterPass1.setText("Password");
        }
    }// GEN-LAST:event_RegisterPass1FocusLost

    private void RegisterPass2FocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_RegisterPass2FocusGained

        if (RegisterPass1.getText().equals("")) {
            RegisterPass1.setText("Password");
        }
    }// GEN-LAST:event_RegisterPass2FocusGained

    private void RegisterPass2ActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_RegisterPass2ActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_RegisterPass2ActionPerformed

    private void RegisterButtonMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_RegisterButtonMouseClicked
        String regNo = RegisterNo.getText();
        String regName = RegisterName.getText();
        String regpass1 = RegisterPass1.getText();
        String regpass2 = RegisterPass2.getText();

        // Validation for registration number
        if (!regNo.matches("\\d+")) {
            JOptionPane.showMessageDialog(f, "Invalid Registration Number");
            return;
        }

        if (regName.equals("") || regName.equals("User Name")) {
            JOptionPane.showMessageDialog(f, "Please enter username");
            return;
        }

        if (!regpass1.equals(regpass2)) {
            JOptionPane.showMessageDialog(f, "Password is not matching");
            return;
        }

        if (!T_C2.isSelected()) {
            JOptionPane.showMessageDialog(f, "Agree to our Terms & Conditions");
            return;
        }

        try {
            Class.forName("com.mysql.cj.jdbc.Driver");
            String query = "SELECT * FROM users WHERE registration_number = ?";

            try (Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/mysql", "root", "@Pm109305");
                    PreparedStatement pstmt = con.prepareStatement(query)) {

                pstmt.setString(1, regNo);
                ResultSet rs = pstmt.executeQuery();

                if (rs.next()) {
                    JOptionPane.showMessageDialog(f, "Registration number already exists.");
                    return;
                } else {
                    query = "INSERT INTO users (registration_number, name, password) VALUES (?, ?, ?)";
                    try (PreparedStatement pp = con.prepareStatement(query)) {
                        pp.setString(1, regNo);
                        pp.setString(2, regName);
                        pp.setString(3, regpass1);
                        int rowsAffected = pp.executeUpdate();
                        if (rowsAffected > 0) {
                            JOptionPane.showMessageDialog(f, "Registration Successful");
                        } else {
                            JOptionPane.showMessageDialog(f, "Something went wrong");
                        }
                    }
                }
            }
        } catch (ClassNotFoundException | SQLException ex) {
            ex.printStackTrace();
        }

    }// GEN-LAST:event_RegisterButtonMouseClicked

    private void NameFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_NameFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_NameFieldActionPerformed

    private void NameFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_NameFieldFocusGained
        if (NameField.getText().equals("Your Name")) {
            NameField.setText("");
        }
    }// GEN-LAST:event_NameFieldFocusGained

    private void ContactFieldFocusGained(java.awt.event.FocusEvent evt) {// GEN-FIRST:event_ContactFieldFocusGained
        if (ContactField.getText().equals("Enter Phone no.")) {
            ContactField.setText("");
        }
    }// GEN-LAST:event_ContactFieldFocusGained

    private void ContactFieldActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ContactFieldActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ContactFieldActionPerformed

    private void BookButtonActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_BookButtonActionPerformed
        int indexS = Sourcep2.getSelectedIndex();
        int indexD = destinationp2.getSelectedIndex();

        if (NameField.getText().equals("Your Name") || ContactField.getText().equals("Enter Phone no.")) {
            JOptionPane.showMessageDialog(f, "Please Login or add Contact details");
            return;
        }
        if (name.equals("")) {
            JOptionPane.showMessageDialog(f, "Please Login");
            activeLoginPanel();
            return;
        }
        if (indexS == indexD) {
            JOptionPane.showMessageDialog(f, "Source and Destination must differ");
            return;
        } else if (indexS == 0 && indexD == 1) {

            fareField.setText("Rs 05");
            JOptionPane.showMessageDialog(f, "Your ride is Just 5 min's away\n    Your Fare: " + fareField.getText());
        } else if (indexS == 1 && indexD == 0) {
            fareField.setText("Rs 05");
            JOptionPane.showMessageDialog(f, "Your ride is Just 10 min's away\n    Your Fare: " + fareField.getText());
        } else if (indexS == 3 && indexD == 1) {
            fareField.setText("Rs 20");
            JOptionPane.showMessageDialog(f, "Your ride is Just 5 min's away\n    Your Fare: " + fareField.getText());
        } else if (indexS == 0 && indexD == 3) {
            fareField.setText("Rs 25");
            JOptionPane.showMessageDialog(f, "Your ride is Just 15 min's away\n    Your Fare: " + fareField.getText());
        } else if (indexS == 3 && indexD == 0) {
            fareField.setText("Rs 25");
            JOptionPane.showMessageDialog(f, "Your ride is Just 5 min's away\n    Your Fare: " + fareField.getText());
        } else if (indexS == 1 && indexD == 2) {
            fareField.setText("Rs 10");
            JOptionPane.showMessageDialog(f, "Your ride is Just 5 min's away\n    Your Fare: " + fareField.getText());
        } else if (indexS == 2 && indexD == 1) {
            fareField.setText("Rs 10");
            JOptionPane.showMessageDialog(f, "Your ride is Just 5 min's away\n    Your Fare: " + fareField.getText());
        } else if (indexS == 0 && indexD == 4) {
            fareField.setText("Rs 05");
            JOptionPane.showMessageDialog(f, "Your ride is Just 15 min's away\n    Your Fare: " + fareField.getText());
        } else if (indexS == 4 && indexD == 0) {
            fareField.setText("Rs 05");
            JOptionPane.showMessageDialog(f, "Your ride is Just 5 min's away\n    Your Fare: " + fareField.getText());
        } else {
            fareField.setText("Rs 15");
            JOptionPane.showMessageDialog(f, "Your ride is Just 15 min's away\n    Your Fare: " + fareField.getText());
        }

        // Booked Info List
        BookedInfoModel.addElement("Name:- " + NameField.getText());
        BookedInfoModel.addElement("Source:- " + Sourcep2.getSelectedItem());
        BookedInfoModel.addElement("Destination:- " + destinationp2.getSelectedItem());
        BookedInfoModel.addElement("Fare:- " + fareField.getText());
        jList2.setModel(BookedInfoModel);

        // Log Info List
        LocalDateTime currentTime = LocalDateTime.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("hh:mm:ss a yyyy-MM-dd");
        LogInfoModel.addElement("Booking Time: " + currentTime.format(formatter));
        LogInfoModel.addElement("Reg no: " + loginRegField.getText());
        LogInfoModel.addElement("Contact:- " + ContactField.getText());

        jList1.setModel(LogInfoModel);
        activeStatusPanel();
    }// GEN-LAST:event_BookButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Taxi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Taxi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Taxi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Taxi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Taxi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AboutPanel;
    private javax.swing.JButton BookButton;
    private javax.swing.JScrollPane BookedInfo;
    private javax.swing.JPanel BookingPanel;
    private javax.swing.JTextField ContactField;
    private javax.swing.JPanel Container;
    private javax.swing.JLabel LPUtextLabel;
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel MainPic;
    private javax.swing.JTextField NameField;
    private javax.swing.JPanel RegItemContainer;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField RegisterName;
    private javax.swing.JTextField RegisterNo;
    private javax.swing.JTextField RegisterPass1;
    private javax.swing.JPasswordField RegisterPass2;
    private javax.swing.JPanel RegistrationPanel;
    private javax.swing.JComboBox<String> Sourcep2;
    private javax.swing.JPanel StatusPanel;
    private javax.swing.JRadioButton T_C2;
    private javax.swing.JRadioButton T_Cbutton;
    private javax.swing.JComboBox<String> destinationp2;
    private javax.swing.JTextField fareField;
    private javax.swing.JLabel goRegiText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JList<String> jList2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField loginPassField;
    private javax.swing.JTextField loginRegField;
    private javax.swing.JLabel lpuLogo;
    private javax.swing.JPanel navigator1;
    private javax.swing.JPanel navigator2;
    private javax.swing.JPanel navigator3;
    private javax.swing.JPanel navigator4;
    // End of variables declaration//GEN-END:variables
}
